name: Docker Build and Push

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/my-webapp:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/my-webapp:${{ github.sha }}

    - name: Test Docker image
      run: |
        docker run --rm -d -p 8080:80 --name test-container ${{ secrets.DOCKERHUB_USERNAME }}/my-webapp:latest
        sleep 5
        docker stop test-container
        echo "Docker container test completed!"

    - name: Verify push
      run: |
        echo "Image successfully pushed to:"
        echo "https://hub.docker.com/r/${{ secrets.DOCKERHUB_USERNAME }}/my-webapp"