name: Build, Push and Deploy

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/my-webapp:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/my-webapp:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: success()  # Запускать только если сборка успешна

    steps:
    - name: Deploy to production server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "🚀 Starting deployment to ${{ secrets.SERVER_IP }}..."
          
          # Логинимся в Docker Hub
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          
          # Останавливаем и удаляем старый контейнер если существует
          if docker ps -a --format '{{.Names}}' | grep -q 'my-webapp-container'; then
            echo "🛑 Stopping existing container..."
            docker stop my-webapp-container
            docker rm my-webapp-container
          fi
          
          # Pull последнего образа
          echo "📦 Pulling latest image..."
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-webapp:latest
          
          # Запускаем новый контейнер
          echo "🐳 Starting new container..."
          docker run -d \
            --name my-webapp-container \
            -p 80:80 \
            --restart unless-stopped \
            ${{ secrets.DOCKERHUB_USERNAME }}/my-webapp:latest
          
          # Проверяем что контейнер запустился
          sleep 5
          if docker ps --filter "name=my-webapp-container" --format "{{.Status}}" | grep -q "Up"; then
            echo "✅ Deployment completed successfully!"
            echo "🌐 Application available at: http://${{ secrets.SERVER_IP }}"
          else
            echo "❌ Deployment failed!"
            docker logs my-webapp-container
            exit 1
          fi
          
          # Очистка старых образов
          docker image prune -af
          echo "🧹 Old images cleaned up"